version: '3'
services:
  nginx-proxy:
    image: nginx:${NGINX_VERSION:-latest}
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_PROXY:-nginx-proxy}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_PROXY_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_PROXY_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_PROXY_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen:${DOCKER_GEN_VERSION}
    command: -notify-sighup ${NGINX_PROXY:--nginx-proxy} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_PROXY:-nginx-proxy}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

  jenkins-master:
    build: ./jenkins/jenkins-master
    container_name: ${JENKINS_MASTER:-jenkins-master}
    ports:
      - "${JENKINS_AGENT_PORT:-50000}:${JENKINS_AGENT_PORT:-50000}"
    restart: always
    volumes:
      - jenkins-data:${JENKINS_DATA_PATH}
      - jenkins-logs:${JENKINS_LOGS_PATH}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${JENKINS_HTTP_PORT:-8080}
      - LETSENCRYPT_HOST=${LETS_ENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST:-true}
    logging:
      driver: ${JENKINS_MASTER_LOG_DRIVER:-json-file}
      options:
        max-size: ${JENKINS_MASTER_LOG_MAX_SIZE:-2m}
        max-file: ${JENKINS_MASTER_LOG_MAX_FILE:-10}

volumes:
  jenkins-data:
  jenkins-logs:

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}